# Generated by Django 2.0.4 on 2018-04-10 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_limb', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_Number', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
                ('Zip_Code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MyEmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_Number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('race', models.CharField(choices=[('1', 'African Amercan'), ('2', 'Amercan Indian'), ('3', 'Asian'), ('4', 'Hispanic'), ('5', 'White')], max_length=1)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(blank=True, max_length=15)),
                ('therapist_username', models.CharField(max_length=15)),
                ('header', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='myemergencycontact',
            name='Firts_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientPortal.MyPersonalInformation'),
        ),
        migrations.AddField(
            model_name='myemergencycontact',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mycontactinformation',
            name='First_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientPortal.MyPersonalInformation'),
        ),
        migrations.AddField(
            model_name='mycontactinformation',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='First_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onrecord', to='patientPortal.MyPersonalInformation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
