# Generated by Django 2.0.3 on 2018-03-31 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0004_auto_20180331_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='patient_ID',
            new_name='user_ID',
        ),
    ]
