# Generated by Django 2.0.3 on 2018-04-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0005_auto_20180331_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
