# Generated by Django 2.0.2 on 2018-04-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0007_auto_20180405_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='affected_limb',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='task',
        ),
    ]
