# Generated by Django 2.0.2 on 2018-03-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='first_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='last_name',
            new_name='patient_ID',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='updated',
        ),
    ]
